import Head from 'next/head';

import CONST_VALUE from '../data/constants';
import { NextPageWithLayout } from '../types';
import AppWrapper from '../components/Common/AppShell';
import LandingFace from '../components/Landing/LandingFace';
import CollectionFilter from '../components/Landing/Collections';

const Landing: NextPageWithLayout = () => (
  <div>
    <Head>
      <title>{CONST_VALUE.pageTitle.landing}</title>
      <meta name="description" content="Generated by Sayanta" />
    </Head>

    <LandingFace />
    <CollectionFilter />
  </div>
);

Landing.getLayout = page => <AppWrapper>{page}</AppWrapper>;

export default Landing;
